version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.11
    restart: always
    container_name: ContainerC
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}