version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    domainname: rabbitmq
    restart: always
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  producer:
    image: python:3.11-slim-buster
    working_dir: /app
    restart: always
    container_name: ContainerA
    volumes:
      - ./scraper.py:/app/scraper.py
      - ./db.py:/app/db.py
      - ./.env:/app/.env
    command: >
      bash -c "
        apt-get update &&
        pip install aiohttp pika pymongo python-dotenv &&
        chmod +x /app/scraper.py &&
        python /app/scraper.py
      "

    depends_on:
      - rabbitmq

  consumer:
    image: python:3.11-slim-buster
    working_dir: /app
    restart: always
    container_name: ContainerB
    ports:
      - "8501:8501"
    volumes:
      - ./consumer.py:/app/consumer.py
      - ./page.py:/app/page.py
      - ./db.py:/app/db.py
      - ./.env:/app/.env
    command: >
      bash -c "
        apt-get update &&
        apt install nano &&
        pip install pika streamlit pycountry python-dotenv pymongo &&
        (python /app/consumer.py &) &&
        streamlit run page.py --server.port=8501 --server.address=0.0.0.0
      "
    depends_on:
      - rabbitmq